name: moovies
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  auto_route: ^7.8.0
  cached_network_image: ^3.2.3
  dartz: ^0.10.1
  dio: ^5.3.2
  dio_smart_retry: ^5.0.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  flutter_hooks: ^0.20.0
  flutter_screenutil: ^5.8.4
  flutter_svg: ^2.0.7
  get_it: ^7.6.0
  json_serializable: ^6.7.1
  logging: ^1.2.0
  pretty_dio_logger: ^1.3.1

dev_dependencies:  
  auto_route_generator: ^7.3.0
  bloc_test: ^9.1.4
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  http_mock_adapter: ^0.4.4
  json_annotation: ^4.8.1
  mockito: ^5.4.2
  mocktail: ^1.0.0

flutter:
  uses-material-design: true
